import { Navbar } from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { AssetCard } from "@/components/AssetCard";
import { Link } from "react-router-dom";
import { ArrowRight, Sparkles, Zap, Palette, Bot } from "lucide-react";
import { assets } from "@/data/assets";
import heroBg from "@/assets/hero-bg.jpg";

const Landing = () => {
  const featured = assets.slice(0, 3);

  return (
    <div className="min-h-screen">
      <Navbar />

      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 z-0">
          <img src={heroBg} alt="" className="h-full w-full object-cover opacity-40" width={1920} height={1280} />
          <div className="absolute inset-0 bg-gradient-to-b from-background/60 via-background/80 to-background" />
          <div className="absolute inset-0 grid-bg opacity-40" />
        </div>

        <div className="container relative z-10 py-24 md:py-36 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full glass mb-8 animate-fade-up">
            <Sparkles className="h-3.5 w-3.5 text-accent" />
            <span className="text-xs font-medium">AI-Generated Game Assets · Beta</span>
          </div>
          <h1 className="font-display text-5xl md:text-7xl lg:text-8xl font-bold tracking-tight mb-6 animate-fade-up" style={{ animationDelay: "0.1s" }}>
            Build worlds at the<br />
            <span className="glow-text">speed of imagination</span>
          </h1>
          <p className="max-w-2xl mx-auto text-lg md:text-xl text-muted-foreground mb-10 animate-fade-up" style={{ animationDelay: "0.2s" }}>
            The marketplace for AI-generated game assets. Browse thousands of stylistically consistent models, textures, and sprites — generated by top designers.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-4 animate-fade-up" style={{ animationDelay: "0.3s" }}>
            <Link to="/marketplace">
              <Button variant="hero" size="xl">
                Explore Marketplace <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
            <Link to="/auth?mode=signup">
              <Button variant="neon" size="xl">Get Started Free</Button>
            </Link>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="container py-20 md:py-28">
        <div className="text-center mb-16">
          <h2 className="font-display text-4xl md:text-5xl font-bold mb-4">How it works</h2>
          <p className="text-muted-foreground text-lg">Three steps from idea to in-engine.</p>
        </div>
        <div className="grid md:grid-cols-3 gap-6">
          {[
            { icon: Palette, title: "Pick a style", desc: "Choose from fantasy, sci-fi, pixel, or realistic — every asset is style-locked." },
            { icon: Bot, title: "Browse AI assets", desc: "Thousands of models, sprites, and textures generated by curated designers." },
            { icon: Zap, title: "Drop into your engine", desc: "Game-ready files for Unity & Unreal. Buy once, use forever." },
          ].map((step, i) => (
            <div key={i} className="glass rounded-lg p-8 hover:border-primary/40 transition-all hover:shadow-glow">
              <div className="h-12 w-12 rounded-lg bg-gradient-primary flex items-center justify-center mb-5 shadow-glow">
                <step.icon className="h-6 w-6 text-primary-foreground" />
              </div>
              <div className="text-xs font-mono text-accent mb-2">STEP 0{i+1}</div>
              <h3 className="font-display text-xl font-semibold mb-2">{step.title}</h3>
              <p className="text-muted-foreground">{step.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Featured */}
      <section className="container py-20">
        <div className="flex items-end justify-between mb-10">
          <div>
            <h2 className="font-display text-4xl md:text-5xl font-bold mb-2">Featured drops</h2>
            <p className="text-muted-foreground">Hand-picked from this week's catalog.</p>
          </div>
          <Link to="/marketplace" className="hidden md:block">
            <Button variant="ghost">View all <ArrowRight className="h-4 w-4" /></Button>
          </Link>
        </div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {featured.map(a => <AssetCard key={a.id} asset={a} requireAuth />)}
        </div>
      </section>

      {/* CTA */}
      <section className="container py-20">
        <div className="relative overflow-hidden rounded-2xl glass p-12 md:p-16 text-center">
          <div className="absolute inset-0 bg-gradient-glow" />
          <div className="relative z-10">
            <h2 className="font-display text-4xl md:text-5xl font-bold mb-4">
              Ready to ship faster?
            </h2>
            <p className="text-muted-foreground text-lg mb-8 max-w-xl mx-auto">
              Join thousands of indie developers building their dream games with AI-generated assets.
            </p>
            <Link to="/auth?mode=signup">
              <Button variant="hero" size="xl">Start exploring <ArrowRight className="h-4 w-4" /></Button>
            </Link>
          </div>
        </div>
      </section>

      <footer className="border-t border-border/50 py-8 mt-12">
        <div className="container flex flex-col md:flex-row items-center justify-between gap-4 text-sm text-muted-foreground">
          <div className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-primary" />
            <span className="font-display font-semibold text-foreground">GADM</span>
            <span>· Generative AI Design Marketplace</span>
          </div>
          <p>© 2026 GADM. Prototype build.</p>
        </div>
      </footer>
    </div>
  );
};

export default Landing;
